version: '3'
services:
  postgres:
    image: postgres:11.4
    environment:
      POSTGRES_PASSWORD: chifumi
      POSTGRES_USER: mifuchi
      POSTGRES_DB: mifuchi
    ports:
      - 5432:5432


  mifuchi:
    image: mifuchi:0.1
    ports:
      - 8080:8080
    depends_on:
      - postgres
