micronaut:
    application:
        name: mifuchi
postgres:
    reactive:
        client:
            port: 5432
            host: mifuchi
            database: mifuchi
            user: mifuchi
            password: chifumi
            maxSize: 5
