micronaut:
    application:
        name: mifuchi
postgres:
    reactive:
        client:
            port: 5432
            host: localhost
            database: mifuchi
            user: mifuchi
            password: chifumi
            maxSize: 5
datasources:
    default:
        url: 'jdbc:postgresql://localhost:5432/mifuchi"'
        username: 'mifuchi'
        password: 'chifumi'
        driverClassName: 'org.postgresql.Driver'

flyway:
    datasources:
        default:
            locations:
                classpath:db.migrations

